"""create_forge_api_key_provider_scope_association_table

Revision ID: 08cc005a4bc8
Revises: 6a92c2663fa5
Create Date: 2025-05-16 13:53:06.169215

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "08cc005a4bc8"
down_revision = "6a92c2663fa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forge_api_key_provider_scope_association",
        sa.Column("forge_api_key_id", sa.Integer(), nullable=False),
        sa.Column("provider_key_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forge_api_key_id"],
            ["forge_api_keys.id"],
            name=op.f(
                "fk_forge_api_key_provider_scope_association_forge_api_key_id_forge_api_keys"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_key_id"],
            ["provider_keys.id"],
            name=op.f(
                "fk_forge_api_key_provider_scope_association_provider_key_id_provider_keys"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "forge_api_key_id",
            "provider_key_id",
            name=op.f("pk_forge_api_key_provider_scope_association"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forge_api_key_provider_scope_association")
    # ### end Alembic commands ###
