"""Drop usage_stats table

Revision ID: 0ce4eeae965f
Revises: b38aad374524
Create Date: 2025-04-08 21:34:42.905629

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0ce4eeae965f"
down_revision = "b38aad374524"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_stats", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_stats_id")
        batch_op.drop_index("ix_usage_stats_model")
        batch_op.drop_index("ix_usage_stats_provider_name")

    op.drop_table("usage_stats")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_stats",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("provider_name", sa.VARCHAR(), nullable=False),
        sa.Column("model", sa.VARCHAR(), nullable=False),
        sa.Column("prompt_tokens", sa.INTEGER(), nullable=True),
        sa.Column("completion_tokens", sa.INTEGER(), nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), nullable=True),
        sa.Column("request_count", sa.INTEGER(), nullable=True),
        sa.Column("success_count", sa.INTEGER(), nullable=True),
        sa.Column("error_count", sa.INTEGER(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.Column("endpoint", sa.VARCHAR(), nullable=False),
        sa.Column("input_tokens", sa.INTEGER(), nullable=True),
        sa.Column("output_tokens", sa.INTEGER(), nullable=True),
        sa.Column("requests_count", sa.INTEGER(), nullable=True),
        sa.Column("cost", sa.FLOAT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_stats", schema=None) as batch_op:
        batch_op.create_index(
            "ix_usage_stats_provider_name", ["provider_name"], unique=False
        )
        batch_op.create_index("ix_usage_stats_model", ["model"], unique=False)
        batch_op.create_index("ix_usage_stats_id", ["id"], unique=False)

    # ### end Alembic commands ###
