"""create wallets table

Revision ID: f1a2b3c4d5e6
Revises: b206e9a941e3
Create Date: 2025-08-21 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'b206e9a941e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wallets',
        sa.Column('account_id', sa.BigInteger(), nullable=False),
        sa.Column('currency', sa.CHAR(length=3), nullable=False, server_default='USD'),
        sa.Column('balance', sa.DECIMAL(precision=20, scale=6), nullable=False, server_default='0'),
        sa.Column('blocked', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('version', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('account_id'),
        sa.ForeignKeyConstraint(['account_id'], ['users.id'], ondelete='CASCADE')
    )
    op.add_column('provider_keys', sa.Column('billable', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_column('provider_keys', 'billable')
    # ### end Alembic commands ###